version: '3'
services:
  influxdb:
    image: influxdb:2.0
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    volumes:
      - ./influxdb-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - influxdb
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana:/var/lib/grafana/dashboards
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml


resmed-influx:
    build: 
      context: .
    container_name: myAir
    depends_on:
      - influxdb
    volumes:
      - ./resmed:/app/
    restart: always
    mem_limit: 100m
    stdin_open: false # Allows keeping the input stream open for troubleshooting
    tty: false        # Allocates a pseudo-TTY to the container for troubleshooting
